name: Build
on:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          path: ~/.npm
          restore-keys: |
            ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
            ${{runner.os}}-npm-
      - name: Install Dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run lint:eslint
      - name: Run Prettier
        run: npm run lint:prettier
      - name: Run Build
        run: npm run build
